### ISSUE TITLE
Has the latest version be uploaded to google play? 

### ISSUE THREAD

**Issue by TannerBrunscheon** [BeOrNot2Be/CocktailBuilder#1]
https://play.google.com/store/apps/details?id=davanna.ca.cocktailbuilder&hl=en_US

It seems as if this has not been updated in 4 years yet I see you pushing out new versions all the time.  Is there any way to get the updated version of the clients besides building them ourselves?

**Comment by TannerBrunscheon** [comment]
Opening the app it seems to be stuck at 1.0.7

**Comment by BeOrNot2Be** [comment]
We are doing alpha testing right now. The new version gonna be deployed, as fast as the bugs will be resolved(which is probably gonna be in this 2 days )

**Comment by TannerBrunscheon** [comment]
Cool! Is this project open source? I would be willing to help with bugs/whatever if you could use some extra eyes.

**Comment by BeOrNot2Be** [comment]
No, it's not open source but the new version just come out, so feel free to try it out
https://play.google.com/store/apps/details?id=davanna.ca.cocktailbuilder

**Comment by TannerBrunscheon** [comment]
Thanks!
